// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWCpL0jQXCl6b37-hdupdPG0GB9TtvBXk',
    appId: '1:716477184344:web:42dcd86b6c5b453a9bcd2d',
    messagingSenderId: '716477184344',
    projectId: 'aprendemas-3b9cf',
    authDomain: 'aprendemas-3b9cf.firebaseapp.com',
    storageBucket: 'aprendemas-3b9cf.firebasestorage.app',
    measurementId: 'G-EVWZ7CLRNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDICHodYF4Xq_BHpJkgtGXLDICYYSHqSvM',
    appId: '1:716477184344:android:9bb14269574c95169bcd2d',
    messagingSenderId: '716477184344',
    projectId: 'aprendemas-3b9cf',
    storageBucket: 'aprendemas-3b9cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxQ99BTaoLNlTLlrU6j98MptxblrbcfHc',
    appId: '1:716477184344:ios:07dc68b3fb61dce49bcd2d',
    messagingSenderId: '716477184344',
    projectId: 'aprendemas-3b9cf',
    storageBucket: 'aprendemas-3b9cf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxQ99BTaoLNlTLlrU6j98MptxblrbcfHc',
    appId: '1:716477184344:ios:07dc68b3fb61dce49bcd2d',
    messagingSenderId: '716477184344',
    projectId: 'aprendemas-3b9cf',
    storageBucket: 'aprendemas-3b9cf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWCpL0jQXCl6b37-hdupdPG0GB9TtvBXk',
    appId: '1:716477184344:web:b0658b849511a7bf9bcd2d',
    messagingSenderId: '716477184344',
    projectId: 'aprendemas-3b9cf',
    authDomain: 'aprendemas-3b9cf.firebaseapp.com',
    storageBucket: 'aprendemas-3b9cf.firebasestorage.app',
    measurementId: 'G-G4Q96YXH76',
  );
}
